export const NotificationTypes = {
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',
  PASSWORD_RESET: 'PASSWORD_RESET',
  

  PAYMENT_METHOD_ADDED: 'PAYMENT_METHOD_ADDED',
  PAYMENT_SUCCESS: 'PAYMENT_SUCCESS',
  PAYMENT_FAILED: 'PAYMENT_FAILED',

  SHIPPING_INFO_UPDATED: 'SHIPPING_INFO_UPDATED',

  ORDER_SUBMITTED: 'ORDER_SUBMITTED',
  ORDER_PROCESSING: 'ORDER_PROCESSING',
  ORDER_SHIPPED: 'ORDER_SHIPPED',
  ORDER_DELIVERED: 'ORDER_DELIVERED',
  ORDER_CANCELLED: 'ORDER_CANCELLED',

  LOW_STOCK: 'LOW_STOCK',
  OUT_OF_STOCK: 'OUT_OF_STOCK',
  STOCK_TAKE_COMPLETED: 'STOCK_TAKE_COMPLETED',
  

  PROFILE_UPDATED: 'PROFILE_UPDATED',
  EMAIL_VERIFIED: 'EMAIL_VERIFIED',

  NEW_MESSAGE: 'NEW_MESSAGE',
  
  NEW_REVIEW: 'NEW_REVIEW',
  REVIEW_REPLY: 'REVIEW_REPLY',

  NEW_ORDER: 'NEW_ORDER',
  NEW_USER_REGISTERED: 'NEW_USER_REGISTERED',
  SYSTEM_ALERT: 'SYSTEM_ALERT'
};

export const NotificationPriorities = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  URGENT: 'URGENT'
};

export const RelatedEntities = {
  ORDER: 'ORDER',
  PRODUCT: 'PRODUCT',
  USER: 'USER',
  PAYMENT: 'PAYMENT',
  SHIPMENT: 'SHIPMENT',
  REVIEW: 'REVIEW',
  MESSAGE: 'MESSAGE'
};